run:
  deadline: 10m

linters:
  enable-all: true
  disable:
    - lll
    - dupl
    - gochecknoglobals
    - gocritic
    - maligned
    - goimports
    - misspell
    - gocyclo
    - gochecknoinits
    - depguard

linters-settings:
    govet:
      check-shadowing: true
    golint:
      min-confidence: 0
    maligned:
      suggest-new: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gofmt:
      auto-fix: false